# import = ["~/c/sesh/sesh.toml"]

[[session]]
name = "dotfiles üè°"
path = "~/.dotfiles"

[[session]]
name = "luxor-apps üíª"
path = "~/development/luxor/luxor-apps"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/devenv.sh"

[[session]]
name = "project-nimbus üíª"
path = "~/development/luxor/project-nimbus"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/devenv.sh"

[[session]]
name = "docs üìÑ"
path = "~/development/luxor/docs"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh"

[[session]]
name = "schema üíª"
path = "~/development/luxor/schema"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh"

[[session]]
name = "tmux config"
path = "~/.dotfiles/tmux/.config/tmux"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh tmux.conf"

[[session]]
name = "sketchybar config"
path = "~/.dotfiles/sketchybar/.config/sketchybar"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh sketchybarrc"

[[session]]
name = "deez notes"
path = "/Users/albertilagan/Library/Mobile Documents/iCloud~md~obsidian/Documents/deez-notes"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh"

[[session]]
name = "neovim config"
path = "~/.dotfiles/nvim/.config/nvim"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh"

[[session]]
name = "fish config"
path = "~/.dotfiles/fish/.config/fish"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh config.fish"

[[session]]
name = "yabai config"
path = "~/.dotfiles/yabai/.config/yabai"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh yabairc"

[[session]]
name = "skhd config"
path = "~/.dotfiles/skhd/.config/skhd"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh skhdrc"

[[session]]
name = "yazi config"
path = "~/.dotfiles/yazi/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "wezterm config"
path = "~/.dotfiles/wezterm/.config/wezterm"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh wezterm.lua"

[[session]]
name = "sesh config"
path = "~/.dotfiles/sesh/.config/sesh"
startup_command = "~/.dotfiles/sesh/.config/sesh/bin/nvim.sh sesh.toml"

[[session]]
name = "Downloads üì•"
path = "~/Downloads"
startup_command = "yazi"
